fragment HomepageParts on Homepage {
  __typename
  heroTitle
  heroSubtitle
  homepageLabels {
    __typename
    heroTagline
    heroParagraph
    heroBtnDestinations
    heroBtnFleet
    scrollDown
    loadingText
    stats {
      __typename
      value
      label
    }
    destinationsTitle
    destinationsHighlight
    destinationsSubtitle
    fleetTitlePrefix
    fleetTitleHighlight
    fleetTitleSuffix
    fleetSubtitle
    fleetSearchPlaceholder
    fleetNoResults
    fleetViewAll
    cruiseLinesTitlePrefix
    cruiseLinesTitleHighlight
    cruiseLinesTitleSuffix
    cruiseLinesSubtitle
    hotelsTitle
    hotelsSubtitle
    hotelsButton
    howItWorksTitle
    howItWorksHighlight
    howItWorksSubtitle
    howItWorksSteps {
      __typename
      title
      desc
    }
    whyChooseTitle
    whyChooseHighlight
    whyChooseSubtitle
    whyChooseItems {
      __typename
      title
      desc
    }
    testimonialsTitle
    testimonialsHighlight
    testimonialsIntro
    testimonials {
      __typename
      name
      text
      date
    }
    blogTitle
    blogHighlight
    blogAllPosts
    blogAuthorLabel
    blogReadMore
    ourStoryTitle
    ourStoryHighlight
    ourStoryParagraph1
    ourStoryParagraph2
    ourStoryTeamLabel
    faqTitle
    faqHighlight
    faqSubtitle
    footerBrand
    footerBrandHighlight
    footerCopyright
    contactTitle
    contactTitleHighlight
    contactDescription
    contactLabelName
    contactLabelPhone
    contactLabelEmail
    contactLabelMessage
    contactPlaceholderName
    contactPlaceholderPhone
    contactPlaceholderEmail
    contactPlaceholderMessage
    contactButtonSend
    contactButtonSending
    contactSuccessMessage
    contactErrorMessage
    contactPhoneValue
    contactEmailValue
    contactAddressValue
  }
  detailPageLabels {
    __typename
    backToHome
    aboutTitle
    noDescriptionFallback
    pointsOfInterestTitle
    weatherTitle
    mapTitle
    featuresTitle
    specsTitle
    specsLength
    specsSpeed
    specsCapacity
    specsTonnage
    noSpecsFallback
    contactCtaTitle
    contactCtaParagraph
    contactCtaButton
    galleryTitle
  }
  fleetPageLabels {
    __typename
    backToHome
    titlePrefix
    titleHighlight
    subtitle
    searchPlaceholder
    noResults
    clearSearch
    shipsCountLabel
    categoryLabel
    speedLabel
    capacityLabel
    fullSpecsLink
  }
  homepageShipIds
  blogPageLabels {
    __typename
    backToBlog
    titlePrefix
    titleHighlight
    subtitle
    searchPlaceholder
    featuredBadge
    readFullArticle
    readMore
    authorLabel
    readTimeLabel
    allPostsLink
    homepageTitlePrefix
    homepageTitleHighlight
  }
  homepageBlogPostIds
  destinations {
    __typename
    id
    title
    description
    image
    weather
    mapImage
    pointsOfInterest
  }
  ships {
    __typename
    id
    name
    cruiseLine
    description
    speed
    capacity
    length
    tonnage
    features
    image
    gallery
  }
  faq {
    __typename
    question
    answer
  }
  blogPosts {
    __typename
    id
    title
    excerpt
    date
    image
    author
    readTime
    body
  }
}

fragment PostParts on Post {
  __typename
  title
  excerpt
  date
  image
  author
  readTime
  body
}
