import { defineConfig } from "tinacms";

export default defineConfig({
  branch: "main",
  clientId: null,
  token: null,
  build: {
    outputFolder: "admin",
    publicFolder: "public",
  },
  media: {
    tina: {
      mediaRoot: "uploads",
      publicFolder: "public",
    },
  },
  schema: {
    collections: [
      {
        name: "homepage",
        label: "דף הבית",
        path: "content/homepage",
        format: "json",
        ui: {
          allowedActions: {
            create: false,
            delete: false,
          },
        },
        fields: [
          {
            type: "string",
            name: "heroTitle",
            label: "כותרת ראשית (Hero)",
            isTitle: true,
            required: true,
          },
          {
            type: "string",
            name: "heroSubtitle",
            label: "כותרת משנה (Hero)",
          },
          {
            type: "object",
            name: "homepageLabels",
            label: "תוכן דף הבית – כל המילים והמשפטים",
            description: "שינוי כאן משפיע על כל הטקסטים שמופיעים בדף הבית. אפשר לשנות כותרות, תיאורים, כפתורים ועוד.",
            fields: [
              { type: "string", name: "heroTagline", label: "תגית מעל הכותרת (Hero)" },
              { type: "string", name: "heroParagraph", label: "פסקה מתחת לכותרת (שורה שנייה)", ui: { component: "textarea" } },
              { type: "string", name: "heroBtnDestinations", label: "כפתור – גלה יעדים" },
              { type: "string", name: "heroBtnFleet", label: "כפתור – הצי שלנו" },
              { type: "string", name: "scrollDown", label: "גלול למטה" },
              { type: "string", name: "loadingText", label: "טקסט טעינה" },
              {
                type: "object",
                name: "stats",
                label: "סטטיסטיקות (4 פריטים)",
                list: true,
                fields: [
                  { type: "string", name: "value", label: "מספר" },
                  { type: "string", name: "label", label: "תיאור (למשל: יעדים בעולם)" },
                ],
              },
              { type: "string", name: "destinationsTitle", label: "כותרת יעדים" },
              { type: "string", name: "destinationsHighlight", label: "מילה מודגשת (למשל: פופולריים)" },
              { type: "string", name: "destinationsSubtitle", label: "תיאור מתחת ליעדים", ui: { component: "textarea" } },
              { type: "string", name: "fleetTitlePrefix", label: "צי – תחילת כותרת" },
              { type: "string", name: "fleetTitleHighlight", label: "צי – מילה מודגשת" },
              { type: "string", name: "fleetTitleSuffix", label: "צי – סוף כותרת" },
              { type: "string", name: "fleetSubtitle", label: "תיאור מתחת לצי", ui: { component: "textarea" } },
              { type: "string", name: "fleetSearchPlaceholder", label: "מקום חיפוש אוניות" },
              { type: "string", name: "fleetNoResults", label: "כשאין תוצאות חיפוש" },
              { type: "string", name: "fleetViewAll", label: "כפתור צפה בכל הצי" },
              { type: "string", name: "cruiseLinesTitlePrefix", label: "חברות ספנות – תחילת כותרת" },
              { type: "string", name: "cruiseLinesTitleHighlight", label: "חברות ספנות – מילה מודגשת" },
              { type: "string", name: "cruiseLinesTitleSuffix", label: "חברות ספנות – סוף כותרת" },
              { type: "string", name: "cruiseLinesSubtitle", label: "תיאור מתחת לחברות" },
              { type: "string", name: "hotelsTitle", label: "כותרת מלונות" },
              { type: "string", name: "hotelsSubtitle", label: "תיאור מלונות", ui: { component: "textarea" } },
              { type: "string", name: "hotelsButton", label: "כפתור מלונות" },
              { type: "string", name: "howItWorksTitle", label: "איך זה עובד – תחילת כותרת" },
              { type: "string", name: "howItWorksHighlight", label: "איך זה עובד – מילה מודגשת" },
              { type: "string", name: "howItWorksSubtitle", label: "תיאור איך זה עובד" },
              {
                type: "object",
                name: "howItWorksSteps",
                label: "שלבי איך זה עובד (4 שלבים)",
                list: true,
                ui: { itemProps: (item) => ({ label: item?.title || "שלב" }) },
                fields: [
                  { type: "string", name: "title", label: "כותרת שלב" },
                  { type: "string", name: "desc", label: "תיאור", ui: { component: "textarea" } },
                ],
              },
              { type: "string", name: "whyChooseTitle", label: "למה לבחור – תחילת כותרת" },
              { type: "string", name: "whyChooseHighlight", label: "למה לבחור – מילה מודגשת" },
              { type: "string", name: "whyChooseSubtitle", label: "תיאור למה לבחור בנו" },
              {
                type: "object",
                name: "whyChooseItems",
                label: "3 סיבות לבחור בנו",
                list: true,
                ui: { itemProps: (item) => ({ label: item?.title || "סיבה" }) },
                fields: [
                  { type: "string", name: "title", label: "כותרת" },
                  { type: "string", name: "desc", label: "תיאור", ui: { component: "textarea" } },
                ],
              },
              { type: "string", name: "testimonialsTitle", label: "מה הלקוחות – תחילת כותרת" },
              { type: "string", name: "testimonialsHighlight", label: "מה הלקוחות – מילה מודגשת" },
              { type: "string", name: "testimonialsIntro", label: "פסקת intro המלצות" },
              {
                type: "object",
                name: "testimonials",
                label: "המלצות לקוחות (רשימה)",
                list: true,
                ui: { itemProps: (item) => ({ label: item?.name || "המלצה" }) },
                fields: [
                  { type: "string", name: "name", label: "שם" },
                  { type: "string", name: "text", label: "תוכן ההמלצה", ui: { component: "textarea" } },
                  { type: "string", name: "date", label: "תאריך" },
                ],
              },
              { type: "string", name: "blogTitle", label: "בלוג – כותרת" },
              { type: "string", name: "blogHighlight", label: "בלוג – מילה מודגשת" },
              { type: "string", name: "blogAllPosts", label: "קישור כל הכתבות" },
              { type: "string", name: "blogAuthorLabel", label: "תווית מחבר (למשל: מערכת האתר)" },
              { type: "string", name: "blogReadMore", label: "קרא עוד" },
              { type: "string", name: "ourStoryTitle", label: "הסיפור שלנו – כותרת" },
              { type: "string", name: "ourStoryHighlight", label: "הסיפור שלנו – מילה מודגשת" },
              { type: "string", name: "ourStoryParagraph1", label: "פסקה ראשונה הסיפור", ui: { component: "textarea" } },
              { type: "string", name: "ourStoryParagraph2", label: "פסקה שנייה הסיפור", ui: { component: "textarea" } },
              { type: "string", name: "ourStoryTeamLabel", label: "צוות המומחים – טקסט" },
              { type: "string", name: "faqTitle", label: "שאלות נפוצות – כותרת" },
              { type: "string", name: "faqHighlight", label: "שאלות נפוצות – מילה מודגשת" },
              { type: "string", name: "faqSubtitle", label: "תיאור מתחת לשאלות" },
              { type: "string", name: "footerBrand", label: "פוטר – שם המותג (חלק ראשון)" },
              { type: "string", name: "footerBrandHighlight", label: "פוטר – מילה מודגשת (למשל: לכול)" },
              { type: "string", name: "footerCopyright", label: "פוטר – זכויות יוצרים", ui: { component: "textarea" } },
              { type: "string", name: "contactTitle", label: "צור קשר – כותרת" },
              { type: "string", name: "contactTitleHighlight", label: "צור קשר – מילה מודגשת" },
              { type: "string", name: "contactDescription", label: "צור קשר – פסקה", ui: { component: "textarea" } },
              { type: "string", name: "contactLabelName", label: "שדה שם מלא" },
              { type: "string", name: "contactLabelPhone", label: "שדה טלפון" },
              { type: "string", name: "contactLabelEmail", label: "שדה אימייל" },
              { type: "string", name: "contactLabelMessage", label: "שדה הודעה" },
              { type: "string", name: "contactPlaceholderName", label: "מקום שם (placeholder)" },
              { type: "string", name: "contactPlaceholderPhone", label: "מקום טלפון" },
              { type: "string", name: "contactPlaceholderEmail", label: "מקום אימייל" },
              { type: "string", name: "contactPlaceholderMessage", label: "מקום הודעה" },
              { type: "string", name: "contactButtonSend", label: "כפתור שלח הודעה" },
              { type: "string", name: "contactButtonSending", label: "כפתור בזמן שליחה" },
              { type: "string", name: "contactSuccessMessage", label: "הודעת הצלחה" },
              { type: "string", name: "contactErrorMessage", label: "הודעת שגיאה" },
              { type: "string", name: "contactPhoneValue", label: "טלפון להצגה" },
              { type: "string", name: "contactEmailValue", label: "אימייל להצגה" },
              { type: "string", name: "contactAddressValue", label: "כתובת להצגה" },
            ],
          },
          {
            type: "object",
            name: "detailPageLabels",
            label: "תוויות דף פרט (יעד / אונייה)",
            description: "שמות הסעיפים והכפתורים בדפי הפרט של יעדים ואוניות. אפשר לשנות כאן את כל הכותרות.",
            fields: [
              { type: "string", name: "backToHome", label: "קישור חזרה (למשל: חזרה לדף הבית)" },
              { type: "string", name: "aboutTitle", label: "כותרת סעיף אודות" },
              { type: "string", name: "noDescriptionFallback", label: "טקסט כשאין תיאור" },
              { type: "string", name: "pointsOfInterestTitle", label: "כותרת נקודות עניין" },
              { type: "string", name: "weatherTitle", label: "כותרת מזג אוויר" },
              { type: "string", name: "mapTitle", label: "כותרת מפת הנתיב" },
              { type: "string", name: "featuresTitle", label: "כותרת מאפיינים ומתקנים (אונייה)" },
              { type: "string", name: "specsTitle", label: "כותרת מפרט טכני" },
              { type: "string", name: "specsLength", label: "תווית אורך" },
              { type: "string", name: "specsSpeed", label: "תווית מהירות" },
              { type: "string", name: "specsCapacity", label: "תווית קיבולת" },
              { type: "string", name: "specsTonnage", label: "תווית תפוסה" },
              { type: "string", name: "noSpecsFallback", label: "טקסט כשאין מפרט" },
              { type: "string", name: "contactCtaTitle", label: "כותרת קופסת צור קשר" },
              { type: "string", name: "contactCtaParagraph", label: "פסקה בקופסה (השתמשו ב־{{name}} לשם האונייה)" },
              { type: "string", name: "contactCtaButton", label: "טקסט כפתור צור קשר" },
              { type: "string", name: "galleryTitle", label: "כותרת גלריית תמונות (אונייה)" },
            ],
          },
          {
            type: "object",
            name: "fleetPageLabels",
            label: "תוכן דף צי האוניות",
            description: "כל הכותרות, התיאורים והתוויות בעמוד צי האוניות (כולל כרטיסי האוניות).",
            fields: [
              { type: "string", name: "backToHome", label: "קישור חזרה (חזרה לדף הבית)" },
              { type: "string", name: "titlePrefix", label: "כותרת – תחילה (למשל: צי ה)" },
              { type: "string", name: "titleHighlight", label: "כותרת – מילה מודגשת (למשל: אוניות)" },
              { type: "string", name: "subtitle", label: "תיאור מתחת לכותרת", ui: { component: "textarea" } },
              { type: "string", name: "searchPlaceholder", label: "מקום חיפוש (placeholder)" },
              { type: "string", name: "noResults", label: "כשאין תוצאות חיפוש" },
              { type: "string", name: "clearSearch", label: "כפתור נקה חיפוש" },
              { type: "string", name: "shipsCountLabel", label: "תווית מספר אוניות (למשל: אוניות מוצגות)" },
              { type: "string", name: "categoryLabel", label: "תווית קטגוריה בכרטיס (למשל: צי האוניות)" },
              { type: "string", name: "speedLabel", label: "תווית מהירות" },
              { type: "string", name: "capacityLabel", label: "תווית קיבולת" },
              { type: "string", name: "fullSpecsLink", label: "קישור מפרט טכני מלא" },
            ],
          },
          {
            type: "string",
            name: "homepageShipIds",
            label: "אוניות להצגה בדף הבית",
            list: true,
            description: "רשימת מזהה אוניות (id) להצגה בחלק הצי בדף הבית. השאר ריק כדי להציג את כל האוניות.",
          },
          {
            type: "object",
            name: "blogPageLabels",
            label: "תוכן דף הבלוג",
            description: "כל הכותרות, התיאורים והתוויות בעמוד הבלוג (כולל כרטיסי הכתבות).",
            fields: [
              { type: "string", name: "backToBlog", label: "קישור חזרה לבלוג" },
              { type: "string", name: "titlePrefix", label: "כותרת – תחילה (למשל: בלוג)" },
              { type: "string", name: "titleHighlight", label: "כותרת – מילה מודגשת (למשל: הפלגות)" },
              { type: "string", name: "subtitle", label: "תיאור מתחת לכותרת", ui: { component: "textarea" } },
              { type: "string", name: "searchPlaceholder", label: "מקום חיפוש (placeholder)" },
              { type: "string", name: "featuredBadge", label: "תגית מומלץ (בכרטיס בולט)" },
              { type: "string", name: "readFullArticle", label: "קרא את הכתבה המלאה" },
              { type: "string", name: "readMore", label: "קרא עוד (בכרטיסים קטנים)" },
              { type: "string", name: "authorLabel", label: "תווית מחבר (למשל: מערכת האתר)" },
              { type: "string", name: "readTimeLabel", label: "זמן קריאה (למשל: 8 דקות / דקות קריאה)" },
              { type: "string", name: "allPostsLink", label: "קישור כל הכתבות (למשל: כל הכתבות)" },
              { type: "string", name: "homepageTitlePrefix", label: "דף בית – כותרת בלוג (תחילה)" },
              { type: "string", name: "homepageTitleHighlight", label: "דף בית – כותרת בלוג (מילה מודגשת, למשל: מסעות)" },
            ],
          },
          {
            type: "string",
            name: "homepageBlogPostIds",
            label: "כתבות להצגה בדף הבית",
            list: true,
            description: "רשימת מזהה כתבות (id – שם הקובץ ללא .md) להצגה בחלק הבלוג בדף הבית. השאר ריק כדי להציג את כל הכתבות.",
          },
          {
            type: "object",
            name: "destinations",
            label: "יעדים",
            list: true,
            ui: {
              itemProps: (item) => ({ label: item?.title || "יעד חדש" }),
            },
            fields: [
              { type: "string", name: "id", label: "מזהה (לקישור)", required: true },
              { type: "string", name: "title", label: "כותרת", required: true },
              { type: "string", name: "description", label: "תיאור", ui: { component: "textarea" } },
              { type: "image", name: "image", label: "תמונה" },
              { type: "string", name: "weather", label: "מזג אוויר ממוצע (למשל: קיץ 12°C - 18°C | חורף -2°C - 4°C)", ui: { component: "textarea" } },
              { type: "image", name: "mapImage", label: "תמונת מפת הנתיב" },
              {
                type: "string",
                name: "pointsOfInterest",
                label: "נקודות עניין מרכזיות",
                list: true,
              },
            ],
          },
          {
            type: "object",
            name: "ships",
            label: "אוניות (צי)",
            list: true,
            ui: {
              itemProps: (item) => ({ label: item?.name || "אונייה חדשה" }),
            },
            fields: [
              { type: "string", name: "id", label: "מזהה (לקישור)", required: true },
              { type: "string", name: "name", label: "שם האונייה", required: true },
              { type: "string", name: "cruiseLine", label: "חברת ספנות" },
              { type: "string", name: "description", label: "תיאור האונייה", ui: { component: "textarea" } },
              { type: "string", name: "speed", label: "מהירות (למשל: 17 קשר)" },
              { type: "string", name: "capacity", label: "קיבולת נוסעים (למשל: 228 נוסעים)" },
              { type: "string", name: "length", label: "אורך (למשל: 362 מטר)" },
              { type: "string", name: "tonnage", label: "תפוסה (למשל: 228,081 טון)" },
              {
                type: "string",
                name: "features",
                label: "מאפיינים ומתקנים",
                list: true,
                description: "רשימת מתקנים כמו זירת החלקה על הקרח, פארק שעשועים, מסעדות שף וכו'",
              },
              { type: "image", name: "image", label: "תמונה ראשית" },
              {
                type: "image",
                name: "gallery",
                label: "גלריית תמונות",
                list: true,
                description: "תמונות נוספות לאונייה – גלריה",
              },
            ],
          },
          {
            type: "object",
            name: "faq",
            label: "שאלות נפוצות",
            list: true,
            ui: {
              itemProps: (item) => ({ label: item?.question?.slice(0, 40) || "שאלה חדשה" }),
            },
            fields: [
              { type: "string", name: "question", label: "שאלה", required: true, ui: { component: "textarea" } },
              { type: "string", name: "answer", label: "תשובה", ui: { component: "textarea" } },
            ],
          },
          {
            type: "object",
            name: "blogPosts",
            label: "פוסטים מומלצים (בלוג)",
            list: true,
            ui: {
              itemProps: (item) => ({ label: item?.title || "פוסט חדש" }),
            },
            fields: [
              { type: "string", name: "id", label: "מזהה (לקישור)", required: true },
              { type: "string", name: "title", label: "כותרת", required: true },
              { type: "string", name: "excerpt", label: "תקציר", ui: { component: "textarea" } },
              { type: "string", name: "date", label: "תאריך" },
              { type: "image", name: "image", label: "תמונה" },
              { type: "string", name: "author", label: "מחבר (למשל: מערכת האתר)" },
              { type: "string", name: "readTime", label: "זמן קריאה (למשל: 8 דקות)" },
              { type: "string", name: "body", label: "תוכן מלא (Markdown)", ui: { component: "textarea" } },
            ],
          },
        ],
      },
      {
        name: "post",
        label: "פוסטים (בלוג)",
        path: "content/posts",
        format: "md",
        fields: [
          { type: "string", name: "title", label: "כותרת", isTitle: true, required: true },
          { type: "string", name: "excerpt", label: "תקציר", ui: { component: "textarea" } },
          { type: "datetime", name: "date", label: "תאריך", ui: { dateFormat: "DD.MM.YYYY" } },
          { type: "image", name: "image", label: "תמונה" },
          { type: "string", name: "author", label: "מחבר (למשל: מערכת האתר)" },
          { type: "string", name: "readTime", label: "זמן קריאה (למשל: 8 דקות)" },
          { type: "rich-text", name: "body", label: "תוכן", isBody: true },
        ],
      },
    ],
  },
});
